### PR TITLE
More edits

### PR DESCRIPTION
**Pull request by 19wolf**
I changed mostly openvpn-install. That should be fine. I changed nextcloud-install but I'm losing focus and falling asleep so I don't know if I finished my edits, double check it. 

I wrote the base for a create-container.sh script. The idea is creating the container in each app script can all be sourced from the same code using a function. It's not ready to go yet (It doesn't take arguments, though it's written with them in place)

### CODE REVIEW

**Comment by X1Aaron** [comment]
@19wolf for some reason I can't merge this request.

`This branch has conflicts that must be resolved`

**Comment by X1Aaron** [comment]
@19wolf I noticed you commented out the sleep before updating the container.

`#sleep 5s #no`

Sadly, this is needed because if you don't wait the container isn't fully "awake" yet and the update fails.

**Comment by X1Aaron** [comment]
You will also see that I have added a wait for getting the container IP, so maybe the second wait isn't needed? We need to test.

**Comment by 19wolf** [comment]
I fixed that in the newest code in lxq's create_container function. Basically just loop until there's an ip address.

**Pull request closed without merging**
